# Generated by Django 6.0.6 on 2026-06-09 02:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du fournisseur')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True, verbose_name='N° Facture')),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de vente')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('OM', 'Orange Money'), ('WAVE', 'Wave'), ('CHEQUE', 'Chèque'), ('COMPTE', 'Compte Clinique')], default='ESPECES', max_length=20, verbose_name='Mode de paiement')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code médicament / Code-barres')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du médicament')),
                ('categorie', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock disponible')),
                ('stock_minimum', models.IntegerField(default=5, verbose_name="Stock minimum d'alerte")),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Prix d'achat (FCFA)")),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente (FCFA)')),
                ('date_expiration', models.DateField(verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée de stock'), ('SORTIE', 'Sortie de stock'), ('AJUSTEMENT', "Ajustement d'inventaire")], max_length=20, verbose_name='Type de mouvement')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du mouvement')),
                ('motif', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif / Commentaire')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pharmacie.medicament', verbose_name='Médicament')),
            ],
            options={
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire (FCFA)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (FCFA)')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.medicament', verbose_name='Médicament')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacie.vente', verbose_name='Vente')),
            ],
        ),
    ]
