# Generated by Django 6.0.6 on 2026-06-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='nom_client',
            field=models.CharField(default='Passant', max_length=150, verbose_name='Nom du client'),
        ),
    ]
