# Generated by Django 6.0.6 on 2026-06-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0002_vente_nom_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vente',
            old_name='nom_client',
            new_name='client_nom',
        ),
        migrations.AddField(
            model_name='vente',
            name='client_adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse du client'),
        ),
        migrations.AddField(
            model_name='vente',
            name='client_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Âge du client'),
        ),
        migrations.AddField(
            model_name='vente',
            name='client_telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone du client'),
        ),
    ]
