# Generated by Django 6.0.6 on 2026-06-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0003_rename_nom_client_vente_client_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='numero_lot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de lot'),
        ),
        migrations.AddField(
            model_name='vente',
            name='est_annulee',
            field=models.BooleanField(default=False, verbose_name='Vente annulée'),
        ),
    ]
