# Generated by Django 6.0.6 on 2026-06-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0004_lignevente_remise_mouvementstock_numero_lot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='client_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Âge du client'),
        ),
    ]
